### PR TITLE
update machine configuration for summit

### PR DESCRIPTION
**Pull request by xyuan**
update the machine configuration xml file for latest project setup.

### CODE REVIEW

**Comment by xyuan** [comment]
pgi fortran on summit build with acme-ecp has netcdf configuration issue as well, it need to be fixed tomorrow.

**Comment by whannah1** [comment]
We have some additional summit fixes that Matt is working that are specific to the CPU MMF runs, but it looks like there's no conflict with the changes here.

**Comment by sarats** [comment]
@xyuan Curious, some of these should be in E3SM master. Won't they be brought in through a regular merge?

**Comment by whannah1** [comment]
@sarats, we just did a merge with E3SM, are these additions in E3SM very recent?

**Comment by xyuan** [comment]
The acme-ecp master is out of date, but the e3sm master branch sounds catching up the latest changes.
________________________________

**Comment by whannah1** [comment]
@xyuan, we have to be careful about trying to keep up with E3SM. There have been many times where we needed to pull things down from E3SM, and ideally we would be syncing more frequently, but the merge process has often created conflicts that were difficult to resolve. So we try to limit these updates to when we have a critical need for them. The ECP fork will often be behind E3SM, and that's ok.

**Comment by xyuan** [comment]
@Hannah, Walter Michael<mailto:hannah6@llnl.gov>, thanks. I understand your point.
________________________________

**Comment by sarats** [comment]
@whannah1 The path changes from csc190 to cli115 should be a long time ago. 
See https://github.com/E3SM-Project/E3SM/blame/master/cime/config/e3sm/machines/config_machines.xml#L2965

**Comment by sarats** [comment]
Some path updates 8 months ago, recent commit to master on June 6:
https://github.com/E3SM-Project/E3SM/commit/55772a4409368c31b701428b7dd978261848b608

**Comment by whannah1** [comment]
@sarat, I guess those changes were overrided by all the changes we've made to the summit config to get the GPU runs working. It might be worth adding a "summit-ecp" machine to avoid these things clashing in the future.

**Comment by sarats** [comment]
There should be a lot of overlap. I'm not sure that ACME-ECP and E3SM have different module or other requirements. The requisite changes should mostly be captured in config_compilers where there is a pgigpu section for Summit.

**Comment by rljacob** [comment]
ACME-ECP is the only version of ACME/E3SM running on summit so the summit config should be what you need.

**Comment by sarats** [comment]
@rljacob I agree but we do certain benchmarking runs with E3SM on Summit. For instance, the standardized performance benchmarks and ongoing I/O benchmarks (SCORPIO + ADIOS). So, we would need to build and test. As I said earlier, there is no real conflicting requirements between ACME-ECP and E3SM in the config_machines, any needed changes can be captured in config_compilers.

**Comment by whannah1** [comment]
@sarat, maybe the issue is just that changes are being made in both repos. I agree there's a lot of overlap, but merging with E3SM has broken our configuration in the past.

**Comment by sarats** [comment]
Then, we should coordinate better. I don't see a fundamental reason for divergence.

**Pull request merged**
